name: build&test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
